name: tcg_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  app_tracking_transparency: ^2.0.2+4

  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4

  state_notifier: ^0.7.2+1

  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

  sqflite: ^2.0.2+1
  path_provider: ^2.0.10

  path: ^1.8.2

  shared_preferences: ^2.0.15

  adaptive_dialog: ^1.6.3

  tab_indicator_styler: ^2.0.0

  syncfusion_flutter_core: ^20.1.57
  syncfusion_flutter_datagrid: ^20.1.57
  syncfusion_flutter_datepicker: ^20.1.57
  syncfusion_flutter_charts: ^20.1.57

  intl: ^0.17.0

  google_fonts: ^3.0.1

  google_mobile_ads: ^1.2.0

  settings_ui: ^2.0.2

  flutter_launcher_icons: ^0.9.2

  url_launcher: ^6.1.2

  launch_review: ^3.0.1

  webview_flutter: ^3.0.4

  flutter_native_splash: ^2.2.1

  modal_bottom_sheet: ^2.0.1

  flutter_screenutil: ^5.5.3+2

  flex_color_scheme: ^5.0.1

  scrollable_positioned_list: ^0.3.2

  keyboard_actions: ^4.0.0

  flutter_slidable: ^1.3.0

  flutter_sticky_header: ^0.6.3

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

  uses-material-design: true
flutter_intl:
  enabled: true
