name: tcg_manager
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2

  state_notifier: ^0.7.2+1

  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4

  sqflite: ^2.0.2
  path_provider: ^2.0.8

  adaptive_dialog: ^1.3.0

  tab_indicator_styler: ^2.0.0

  syncfusion_flutter_datagrid: ^19.4.47

  intl: ^0.17.0

  google_fonts: ^2.2.0

  google_mobile_ads: ^1.0.1

  settings_ui: ^2.0.2

  flutter_launcher_icons: ^0.9.2

  url_launcher: ^6.0.18

  launch_review: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  build_runner: ^2.1.7
  freezed: ^1.1.1

  device_preview: ^1.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf

  uses-material-design: true
flutter_intl:
  enabled: true
