name: tcg_manager
description: A new Flutter project.

publish_to: 'none'

version: 2.0.7+15

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  app_tracking_transparency: ^2.0.4

  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6

  state_notifier: ^0.7.2+1

  freezed_annotation: ^2.2.0
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3

  http: ^1.1.0

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_messaging: ^14.6.4
  firebase_storage: ^11.2.4
  firebase_dynamic_links: ^5.3.3
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4

  shared_preferences: ^2.2.0

  adaptive_dialog: ^1.8.3+1

  tab_indicator_styler: ^2.0.0

  syncfusion_flutter_core: ^22.1.37
  syncfusion_flutter_datagrid: ^22.1.37
  syncfusion_flutter_datepicker: ^22.1.37
  syncfusion_flutter_charts: ^22.1.37
  syncfusion_flutter_sliders: ^22.1.37

  intl: 0.18.0

  google_fonts: ^5.1.0

  google_mobile_ads: ^2.3.0

  sign_in_button: ^3.2.0

  settings_ui: ^2.0.2

  flutter_launcher_icons: ^0.13.1

  url_launcher: ^6.1.12

  launch_review: ^3.0.1

  in_app_review: ^2.0.6

  webview_flutter: ^3.0.4

  flutter_native_splash: ^2.3.1

  modal_bottom_sheet: ^3.0.0-pre

  flutter_screenutil: ^5.8.4

  flex_color_scheme: ^7.1.2

  scrollable_positioned_list: ^0.3.8

  keyboard_actions: ^4.2.0

  flutter_slidable: ^3.0.0

  flutter_sticky_header: ^0.6.5

  easy_debounce: ^2.0.3

  collection: ^1.17.1

  purchases_flutter: ^5.2.3

  image_picker: ^1.0.0

  dotted_border: ^2.0.0+3

  flutter_smart_dialog: ^4.9.3+1

  easy_image_viewer: ^1.2.1

  share_plus: ^7.0.2

  font_awesome_flutter: ^10.5.0

  csv: ^5.0.2

  intl_phone_field: ^3.2.0

  flutter_svg: ^2.0.7

  package_info_plus: ^4.0.2

  version: ^3.0.2

  cached_network_image: ^3.2.3

  image_cropper: ^5.0.0

# ビルドエラー回避のために追加
dependency_overrides:
  macos_ui:
    git:
      url: https://github.com/Mayb3Nots/macos_ui.git
      ref: dev

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
  
  assets:
    - assets/images/login_view_image.svg

  uses-material-design: true
flutter_intl:
  enabled: true

