name: tcg_manager
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+6

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  app_tracking_transparency: ^2.0.2+4

  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.4

  state_notifier: ^0.7.2+1

  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0

  sqflite: ^2.0.2+1
  path_provider: ^2.0.10

  path: ^1.8.0

  shared_preferences: ^2.0.15

  adaptive_dialog: ^1.6.4+2

  tab_indicator_styler: ^2.0.0

  syncfusion_flutter_core: ^20.2.38
  syncfusion_flutter_datagrid: ^20.2.38
  syncfusion_flutter_datepicker: ^20.2.38
  syncfusion_flutter_charts: ^20.2.38
  syncfusion_flutter_sliders: ^20.2.38

  intl: ^0.17.0

  google_fonts: ^3.0.1

  google_mobile_ads: ^2.3.0

  settings_ui: ^2.0.2

  flutter_launcher_icons: ^0.11.0

  url_launcher: ^6.1.4

  launch_review: ^3.0.1

  in_app_review: ^2.0.4

  webview_flutter: ^3.0.4

  flutter_native_splash: ^2.2.4

  modal_bottom_sheet: ^2.1.0

  flutter_screenutil: ^5.5.3+2

  flex_color_scheme: ^6.1.2

  scrollable_positioned_list: ^0.3.2

  keyboard_actions: ^4.0.1

  flutter_slidable: ^2.0.0

  flutter_sticky_header: ^0.6.3

  easy_debounce: ^2.0.2+1

  collection: ^1.16.0

  purchases_flutter: ^4.0.0-rc.2

  image_picker: ^0.8.5+3

  dotted_border: ^2.0.0+2

  flutter_smart_dialog: ^4.5.4+2

  easy_image_viewer: ^1.1.0

  share_plus: ^6.3.0

  csv: ^5.0.1

flutter_native_splash:
  image: "assets/images/icon.png"
  color: "FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Black.otf
        - asset: assets/fonts/NotoSansJP-Bold.otf
        - asset: assets/fonts/NotoSansJP-Light.otf
        - asset: assets/fonts/NotoSansJP-Medium.otf
        - asset: assets/fonts/NotoSansJP-Regular.otf
        - asset: assets/fonts/NotoSansJP-Thin.otf
  
  assets:
    - assets/images/multiple_tag.png

  uses-material-design: true
flutter_intl:
  enabled: true

